# Generated by Django 5.0.1 on 2024-01-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Victim_Credentials',
        ),
    ]
