# Generated by Django 5.0.1 on 2024-01-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_user_victim_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim_credentials',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='victim_credentials',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
